In [3]:
import scipy
scipy.__version__

'1.3.1'

In [2]:
classes = ['plane', 'car', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']
for y, cls in enumerate(classes):
    print(y)
    print(cls)

0
plane
1
car
2
bird
3
cat
4
deer
5
dog
6
frog
7
horse
8
ship
9
truck


In [2]:
import numpy as np
y_train = np.array([0, 1, 1, 2, 2, 2, 5, 2, 7, 6, 2, 3]) 
print(y_train.shape)
print(y_train == 2)
idxs = np.flatnonzero(y_train == 2)
print(idxs)
idxs = np.random.choice(idxs, 3, replace=False)
print(idxs)
for i, idx in enumerate(idxs):
    print(i)
    print(idx)

(12,)
[False False False  True  True  True False  True False False  True False]
[ 3  4  5  7 10]
[4 7 3]
0
4
1
7
2
3


In [23]:
num_training = 10
a = range(num_training)
print(a)
mask = list(range(num_training))
print(mask)

range(0, 10)
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [9]:
a = np.array([0, 1, 4, 2, 2, 2, 5, 2, 7, 6, 2, 3])
a

array([0, 1, 4, 2, 2, 2, 5, 2, 7, 6, 2, 3])

In [10]:
closest = np.argpartition(a, 3)
print(closest)
a[closest[:3]]

[ 0  1 10  7  5  4  6  3  8  9  2 11]


array([0, 1, 2])

In [13]:
b = np.bincount(a)
b


array([1, 1, 5, 1, 1, 1, 1, 1], dtype=int64)

In [14]:
c = np.argmax(b)
c

2

In [19]:
print(a)
a.shape

[0 1 4 2 2 2 5 2 7 6 2 3]


(12,)

In [20]:
m = np.matrix(a)
print(m)
m.shape

[[0 1 4 2 2 2 5 2 7 6 2 3]]


(1, 12)

In [35]:
a1 = np.array([1,1,1,1,1])
a2 = np.array([2,2,2,2,2,2,2])
print(a1.shape)

(5,)


In [36]:
bb = np.matrix(a1)
print(bb)
print(bb.shape)
cc = np.matrix(a2).T
print(cc)
print(cc.shape)

[[1 1 1 1 1]]
(1, 5)
[[2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]]
(7, 1)


In [38]:
dd = bb + cc
print(dd)

[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]


In [60]:
test = np.zeros((1000,4000), dtype = np.int)
print(test.shape)
closest_y = np.argpartition(test[0,:], 2)
print(closest_y)
closest_y = closest_y[:2]
print(closest_y)

labels = np.array([15,10,20])
print(labels)
k_labels = labels[closest_y]
print(k_labels)
y_pred = np.argmax(np.bincount(k_labels))
print(y_pred)

(1000, 4000)
[   0    1    2 ... 3997 3998 3999]
[0 1]
[15 10 20]
[15 10]
10


In [3]:
pp = np.arange(100)
print(pp)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [4]:
y = np.ones(100,)

In [8]:
scores = np.zeros([100, 10])

In [12]:
ss = scores[np.arange(100, dtype=np.int32), y]

IndexError: arrays used as indices must be of integer (or boolean) type

In [6]:
batch_indicies = np.random.choice(10, 3, replace = False)
print(batch_indicies)

[3 5 4]
