In [3]:
import numpy as np

In [15]:
num_inputs = 2
input_shape = (4, 5, 6)
output_dim = 3

input_size = num_inputs * np.prod(input_shape)
print(input_size)
x = np.linspace(-0.1, 0.5, num=input_size)
print(x.shape)
print("......")
x = x.reshape(num_inputs, *input_shape)
print(x.shape)
#print(x)

240
(240,)
......
(2, 4, 5, 6)


In [44]:
np.random.seed(231)
x = np.random.randn(10, 2, 3)
w = np.random.randn(6, 5)
b = np.random.randn(5)
dout = np.random.randn(10, 5)

print(x)
print(w)
print(b)
print(dout)

[[[ 0.41794341  1.39710028 -1.78590431]
  [-0.70882773 -0.07472532 -0.77501677]]

 [[-0.1497979   1.86172902 -1.4255293 ]
  [-0.3763567  -0.34227539  0.29490764]]

 [[-0.83732373  0.95218767  1.32931659]
  [ 0.52465245 -0.14809998  0.88953195]]

 [[ 0.12444653  0.99109251  0.03514666]
  [ 0.26207083  0.14320173  0.90101716]]

 [[ 0.23185863 -0.79725793  0.12001014]
  [-0.65679608  0.26917456  0.333667  ]]

 [[ 0.27423503  0.76215717 -0.69550058]
  [ 0.29214712 -0.38489942  0.1228747 ]]

 [[-1.42904497  0.70286283 -0.85850947]
  [-1.14042979 -1.58535997 -0.01530138]]

 [[-0.32156083  0.56834936 -0.19961722]
  [ 1.27286625  1.27292534  1.58102968]]

 [[-1.75626715  0.9217743  -0.6753054 ]
  [-1.43443616  0.47021125  0.03196734]]

 [[ 0.04448574  0.47824879 -2.51335181]
  [-1.15740245 -0.70470413 -1.04978879]]]
[[-1.90795589  0.49258765  0.83736166 -1.4288134  -0.18982427]
 [-1.14094943 -2.12570755 -0.41354791  0.44148975  0.16411113]
 [-0.65505065 -0.30212765 -0.25704466 -0.12841368  0.2

In [45]:
np.random.seed(231)
x1 = np.random.randn(10, 2, 3)

s = x1.shape
print(x1.shape)
x1 = np.reshape(x1, (x1.shape[0], -1))
print(x1.shape)
x1 = np.reshape(x1, s)
print(x1.shape)

(10, 2, 3)
(10, 6)
(10, 2, 3)


In [57]:
print(dout)  #(10,5)
print(dout.shape) 
aa = np.argmax(dout, axis=0) # axis=0 reduce 10
bb = np.argmax(dout, axis=1) # axis=1 reduce 5
#print(aa)
print(bb)

#print(x)
#print(x.shape)
xx = np.argmax(x, axis=0) # axis=0 reduce 10
yy = np.argmax(x, axis=1) # axis=1 reduce 2
zz = np.argmax(x, axis=2) # axis=2 reduce 3
#print(xx)
#print(yy)
#print(zz)

y_pred = []
y_pred.append(bb)
print(y_pred)
y_pred = np.hstack(y_pred)
print(y_pred)
y = np.zeros((10))
print(y_pred == y)
acc = np.mean(y_pred == y)
print(acc)

[[-1.80480094  0.53770564 -0.12171369 -1.04250949  0.13828792]
 [-0.22557183 -1.1928829  -0.68320696  0.19909408  0.03070661]
 [-0.44972639  0.14447532 -0.35229594  0.4882136  -0.4347099 ]
 [-0.28692265 -0.84338097 -0.10827394  0.85434757 -0.90377338]
 [-1.0525584  -0.30409794  0.18083726 -0.4125417   1.22913948]
 [-0.97791748 -0.63978524 -0.00880963  0.36213294  0.35148162]
 [-1.20064035 -0.84272962  1.61832501 -2.39079478  0.88256212]
 [-1.12082008  0.12416778 -2.43434598 -1.62701704 -1.10613945]
 [ 2.00862337  0.91447992 -0.86943856  0.13741017 -0.72261465]
 [-0.6755518  -0.04084145 -1.15755894 -0.67498124  0.44252644]]
(10, 5)
[1 3 3 3 4 3 2 1 0 4]
[array([1, 3, 3, 3, 4, 3, 2, 1, 0, 4], dtype=int64)]
[1 3 3 3 4 3 2 1 0 4]
[False False False False False False False False  True False]
0.1


In [59]:
print(np.random.randn(2, 5))

[[-2.12570755 -0.41354791  0.44148975  0.16411113 -0.65505065]
 [-0.30212765 -0.25704466 -0.12841368  0.26338593  0.1672181 ]]


In [66]:
p = 'W'
i = 1
index = i
str = f'W{index}'
print(str)

W1


In [5]:
bn_params = []
bn_params = [{'mode': 'train'} for i in range(5)]
print(bn_params)
print(bn_params[0])
print(bn_params[1])

[{'mode': 'train'}, {'mode': 'train'}, {'mode': 'train'}, {'mode': 'train'}, {'mode': 'train'}]
{'mode': 'train'}
{'mode': 'train'}


In [2]:
weight_scales = np.logspace(-4, 0, num=20)
for i, weight_scale in enumerate(weight_scales):
    print(i)
    print(weight_scale)

0
0.0001
1
0.0001623776739188721
2
0.00026366508987303583
3
0.00042813323987193956
4
0.0006951927961775605
5
0.0011288378916846883
6
0.0018329807108324356
7
0.002976351441631319
8
0.004832930238571752
9
0.007847599703514606
10
0.012742749857031334
11
0.0206913808111479
12
0.03359818286283781
13
0.05455594781168514
14
0.08858667904100823
15
0.14384498882876628
16
0.23357214690901212
17
0.3792690190732246
18
0.615848211066026
19
1.0


In [4]:
a = np.array([1,2,3,4,5])

In [5]:
a.shape

(5,)

In [6]:
a[:]

array([1, 2, 3, 4, 5])

In [8]:
a[:, None].shape

(5, 1)

In [10]:
a[None, :].shape

(1, 5)

In [12]:
a.reshape(1, -1).shape

(1, 5)

In [13]:
a.reshape(-1, 1).shape

(5, 1)

In [19]:
b = np.ones((3, 4, 1))

In [23]:
b.shape

(3, 4, 1)

In [21]:
b.squeeze().shape

(3, 4)